name: Docker Build and Publish

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        container-runtime: containerd

    - name: Build Docker image
      run: docker build -t kjg-dossenheim-pretix .

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag and push Docker image
      run: |
        docker tag kjg-dossenheim-pretix ghcr.io/${{ github.repository_owner }}/kjg-dossenheim-pretix:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/kjg-dossenheim-pretix:${{ github.sha }}
